FROM mysql:8.0
COPY backend/extras/microservices_init.sql /docker-entrypoint-initdb.d/01_init.sql
COPY backend/extras/seed_datos_completos.sql /docker-entrypoint-initdb.d/02_seed.sql
COPY backend/extras/resed_contenido_utf8.sql /docker-entrypoint-initdb.d/03_content_utf8.sql
CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
